config/routes.rb
Rails.application.routes.draw do
  resources :articles
  get 'welcome/index'

  resources :users
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy

  def self.find_or_create_from_auth(auth)
    provider = auth[:provider]
    uid = auth[:uid]
    nickname = auth[:info][:nickname]
    image_url = auth[:info][:image]

    self.find_or_create_by(provider: provider, uid: uid) do |user|
      user.nickname = nickname
      user.image_url = image_url
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  private

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    !!session[:user_id]
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: 'ログインしてください'
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'あざす！！！！！' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'あざす' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'ふぇぇん' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from_auth(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:provider, :uid, :nickname, :image_url)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles = Article.last(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  # Redcarpetを使ってマークダウンの文字列をHTMLに整形します
  #
  # @param text [String] 元markdown文字列
  # @return [String] HTMLセーフで整形されたやつ
  def markdown(text)
    options = {
        # filter_html:     true,
        hard_wrap:       true,
        # link_attributes: { rel: 'nofollow', target: "_blank" },
        # space_after_headers: true,
        # fenced_code_blocks: true
    }

    extensions = {
        autolink: true,
        no_intra_emphasis: true,
        strikethrough: true
        # superscript:        true,
        # disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.slim
.row
  = form_for @article do |f|
    - if @article.errors.any?
      #error_explanation
        h2 = "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
        ul
          - @article.errors.full_messages.each do |message|
            li = message

    .form-group
      .field
        = f.label 'タイトル'
        = f.text_field :title, class: 'form-control'
    .form-group
      .field
        = f.label '内容'
        span.help-block
          | Markdown記法がつかえます。
          br
          | 行末にスペース2つ入れなくても改行します
        = f.text_area :content, class: 'form-control', rows: '15'
    / .actions = f.submit
    = f.button :class => 'btn btn-default' do
      | できた
    | &nbsp;
    = link_to 'やめる',  articles_path, class: 'btn btn-link'

app/views/articles/_top_author.html.slim
table
  tr
    td.top-author-icon rowspan=2
      = image_tag(@article.user.image_url, size: "32", alt: @article.user.nickname, class: 'img-circle')
    td.top-author-nickname
      | &#64;
      = @article.user.nickname
  tr
    td.top-author-updated-at.text-muted
      small
        = @article.updated_at.strftime('%Y/%m/%d %H:%M')
        - if @article.user == current_user
          | &nbsp;(
          = link_to 'なおす', edit_article_path(@article)
          | )

app/views/articles/edit.html.slim
.row
  h1 なおす

== render 'form'

/ link_to 'Show', @article
/ '|
/  link_to 'Back', articles_path

app/views/articles/index.html.slim
h1 Listing articles

table
  thead
    tr
      th Title
      th Content
      th
      th
      th

  tbody
    - @articles.each do |article|
      tr
        td = article.title
        td = article.content
        td = link_to 'Show', article
        td = link_to 'Edit', edit_article_path(article)
        td = link_to 'Destroy', article, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Article', new_article_path

app/views/articles/new.html.slim
.row
  h1 記事をかく

== render 'form'

/ link_to 'Back', articles_path

app/views/articles/show.html.slim
- unless notice.nil?
  .row
    #notice.alert.alert-success[role="alert"]
      a[href="#", class="alert-link"]
        = notice

.row
  = render partial: 'articles/top_author'
h1.row
  = @article.title

.row.article-content
  = markdown @article.content

/ link_to 'Edit', edit_article_path(@article)
/ '|
/ link_to 'Back', articles_path

app/views/layouts/_footer.html.slim
footer
  .container-fluid
    .row
      .col-md-8.col-md-offset-2
        p.text-muted.text-center
          | &copy; 2016 keisei　
          = link_to '利用規約', 'https://twitter.com/keisei_1092', { :target => '_blank' }
          |　
          = link_to 'プライバシー', 'https://twitter.com/keisei_1092', { :target => '_blank' }
          |　
          = link_to 'ヘルプ', 'https://twitter.com/keisei_1092', { :target => '_blank' }
          |　
          = link_to 'お問い合わせ', 'https://twitter.com/keisei_1092', { :target => '_blank' }

app/views/layouts/_header.html.slim
nav.navbar.navbar-default
  .container-fluid
    .row
      .col-lg-8.col-lg-offset-2
        .navbar-header
          button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"]
            span.sr-only
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to 'heyguys', root_path, :class => 'navbar-brand'
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          ul.nav.navbar-nav
            / li.active
              a[href="#"]
                | Link
                span.sr-only
                  | (current)
            / li
               a[href="#"]
                | Link
            / li.dropdown
              a.dropdown-toggle[href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"]
                | Dropdown
                span.caret
              ul.dropdown-menu
                li
                  a[href="#"]
                    | Action
                li
                  a[href="#"]
                    | Another action
                li
                  a[href="#"]
                    | Something else here
                li.divider[role="separator"]
                li
                  a[href="#"]
                    | Separated link
                li.divider[role="separator"]
                li
                  a[href="#"]
                    | One more separated link
          / form.navbar-form.navbar-left
            .form-group
              input.form-control[type="text" placeholder="SONAR 落ちる"]
            button.btn.btn-default[type="submit"]
              | digる
          ul.nav.navbar-nav.navbar-right
            - if logged_in?
              li
                = link_to new_article_path
                  = fa_icon "edit", text: "記事をかく", class: 'fa-lg'
            li.dropdown
              a.dropdown-toggle[href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"]
                - if logged_in?
                  = image_tag(current_user.image_url, size: "24", alt: current_user.nickname, class: 'img-circle')
                - else
                  | ₍˄·͈༝·͈˄₎◞ ̑̑ෆ⃛
                span.caret
              ul.dropdown-menu
                li
                  - if logged_in?
                    = link_to 'じぶん', user_path(current_user)
                  - else
                    = link_to 'guyになる', '/auth/twitter'
                / li
                  = link_to 'いじる', setting_path
                / li
                  = link_to 'なにこれ', help_path
                li.divider[role="separator"]
                li
                  = link_to 'じゃあの', logout_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[http-equiv="Content-Type" content="text/html; charset=utf-8"]
    title heyguys
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
  body
    = render partial: 'layouts/header'
    .container
      .row
        .col-md-10.col-md-offset-1
          = yield
    = render partial: 'layouts/footer'

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :provider %>
    <%= f.text_field :provider %>
  </div>

  <div class="field">
    <%= f.label :uid %>
    <%= f.text_field :uid %>
  </div>

  <div class="field">
    <%= f.label :nickname %>
    <%= f.text_field :nickname %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.slim
p#notice
  = notice
h1
  | Users
table
  thead
  tr
    th
     | Provider
    th
     | Uid
    th
      | Nickname
    th
      | Image url
    th[colspan="3"]
    tbody
      - @users.each do |user|
        tr
          td
            = user.provider
          td
            = user.uid
          td
            = user.nickname
          td
            = user.image_url
          td
            = link_to 'Show', user
          td
            = link_to 'Edit', edit_user_path(user)
          td
            = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
= link_to 'New User', new_user_path
- if logged_in?
  = link_to 'logout', logout_path
- else
  = link_to 'login with Twitter', 'auth/twitter'

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.slim
p#notice
  = notice
.row[style="width: 100%; text-align: center; padding-top: 32px;"]
  p
    = image_tag(@user.image_url, size: "48", alt: current_user.nickname, class: 'img-circle')
  h4
    | &#64;
    = @user.nickname

app/views/welcome/index.html.slim
.row
  .col-md-9
    .jumbotron
      p DTM知識を共有しよう。
      p
        button.btn.btn-default[type="button", onclick="location.href='#{new_article_path}'"]
          | ノウハウ・Tipsを投稿する
    #home-articles.list-group
      - @articles.each do |article|
        = link_to article, class: "list-group-item" do
          h4.list-group-item-heading
            = article.title
            | &nbsp;
            small
              = image_tag(article.user.image_url, size: "16", alt: article.user.nickname, class: 'img-circle')
              | &nbsp;
              = article.user.nickname
              | &nbsp;&#45;&nbsp;
              = article.updated_at.strftime('%Y/%m/%d %H:%M')
          p.list-group-item-text
            = truncate(article.content, length: 140)
  .col-md-3
    ul.list-group
      li.list-group-item
        .media
          .media-left
            img.media-object src="http://placehold.it/32x32"/
          .media-body
            h4.media-heading keisei_1092
            | ほげほげ
    ul.list-group
      li.list-group-item フィード一覧
      li.list-group-item サークル一覧
      li.list-group-item 人気の投稿